#include <ctype.h>      // Character classification and conversion functions (isalpha, isdigit, etc.)
#include <fcntl.h>      // File control functions (open, close, etc.)
#include <unistd.h>     // POSIX operating system API (read, write, etc.)
#include <dirent.h>     // Directory manipulation functions (opendir, readdir, etc.)
#include <sys/types.h>  // Basic data types (pid_t, size_t, etc.)
#include <sys/stat.h>   // File status and file access functions (stat, chmod, etc.)
#include <sys/time.h>   // Time measurement functions (gettimeofday, etc.)
#include <sys/wait.h>   // Process control functions (wait, waitpid, etc.)
#include <sys/socket.h> // Socket programming functions (socket, bind, etc.)
#include <netinet/in.h> // Internet address structures (struct sockaddr_in, etc.)
#include <arpa/inet.h>  // Internet address manipulation (inet_pton, etc.)
#include <netdb.h>      // Network database operations (getaddrinfo, etc.)
#include <pthread.h>    // POSIX thread functions (pthread_create, pthread_join, etc.)
#include <semaphore.h>  // POSIX semaphore functions (sem_init, sem_wait, etc.)
#include <sys/ipc.h>    // Inter-process communication functions (ftok, msgget, etc.)
#include <sys/msg.h>    // Message queue functions (msgsnd, msgrcv, etc.)
#include <sys/shm.h>    // Shared memory functions (shmget, shmat, etc.)
#include <sys/sem.h>    // Semaphore functions (semget, semctl, etc.)
#include <unistd.h>     // POSIX system call functions (fork, exec, etc.)
#include <sys/mman.h>   // Memory management functions (mmap, munmap, etc.)
#include <regex.h>      // Regular expression functions (regcomp, regexec, etc.)
#include <poll.h>       // Polling and event handling functions (poll, etc.)
#include <sys/select.h> // Select and I/O multiplexing functions (select, FD_SET, etc.)
#include <stdlib.h>