version: '3'
services:
  
  #PHP Service
  chat_runtime:
    build:
      context: .
      dockerfile: Dockerfile
   # image: digitalocean.com/php
   # command: sh -c "composer install && chmod -R 644 bootstrap/cache -f && chmod -R 755 storage -f && chmod -R 755 vendor -f"
    container_name: php_chat_backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: chat_runtime
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
         - ./:/var/www 
         - ./php/php.ini:/usr/local/etc/php/php.ini
    #    - ../../testn.php :/var/www/public/testn.php
     #  - ./../../.env:/var/www/.env
      
    networks:
      - app-network
    

  #Nginx Service
  chap_server:
    image: nginx:alpine
    platform: linux/x86_64
    restart: unless-stopped
    container_name: nginx_chat_server
    tty: true
    ports:
      - "601:80"
      - "602:80"
      - "603:80"
      - "604:80"
      - "605:80"
      - "448:443"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
     # - ./share/conf.d/default.nginx.conf:/etc/nginx/conf.d/default.conf
     # - ./share/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
     # - ./share/conf.d/nginx:/etc/nginx/nginx.conf
   #   - ./testn.php :/var/www/public/index.php
    #  - ../../testn.html :/var/www/public/index.html
    depends_on: 
        - chat_runtime
        - chat_db
    networks:
      - app-network

  #MySQL Service
  chat_db:
    image: mysql:8.0.11
    platform: linux/x86_64
    container_name: mysql_chat_db
    restart: unless-stopped
    tty: true #eletypewriter
    ports:
      - "3304:3306"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_HOST: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: chat_db
    volumes:
     # - ./.env:/var/www/.env
      - ./data_/mysql:/var/lib/mysql
    #   - ./docker/use/mysql/my.cnf:/etc/mysql/my.cnf 
    networks:
      - app-network
   
  chat_pma:
        depends_on:
            - chat_db
        image: phpmyadmin/phpmyadmin
        container_name: chat_pma_view_db
        environment:
            - PMA_ARBITRARY= 1
            - PMA_HOST=mysql_chat_db
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
            - PMA_PORT=3306
      
        networks: 
          - app-network
        ports:
            - 9999:80

  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_master_password
    volumes:
      - '/redis_store:/bitnami'

  redis-replica:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_master_password
      - REDIS_PASSWORD=my_replica_password

#Docker Networks
networks:
  app-network:
    driver: bridge
volumes:
  data_:
    #driver: local

    #xampp/htdocs/project 




