
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc #service resource name as service-name
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment # deployment resource name  as service-name
  labels:
    app: nginx
spec:
  replicas: 4
  selector: #deployment select pod through selector to pod metadata.label
    matchLabels:
      app: nginx 

  template:
  #############################################pod start
  #pod start here
    metadata:
      labels:
        app: nginx  # matchLabel for service selector
    spec:
    ########################## POD contains many conatiner
      containers:
      - name: nginx
    ###########################container contains images
        image: nginx:1.14.2
        command: 
          - /bin/sh
          - c
          - touch /tmp/data/; sleeep 3; rm -rf /tmp/data/ sleep 6;echo $(uname -i)
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
      ###############check if the container is healthy
        livenesssProbe:
          exec: 
            command:
              - /bin/sh
              - cat /tmp/data; ping hostname
        readinessProb:
